### ISSUE TITLE
CUPS Addon not saving Settings like Printers

### ISSUE THREAD

**Issue by Delta1977** [MaxWinterstein/homeassistant-addons#217]
Hi, actual Cups-Addon did not save settings like Printer and so on.

**Comment by MaxWinterstein** [comment]
Yes, this is problem, that will be fixed with the next update. Sadly it's pretty hard to find some spare time these days.

(I just need to align my code with the upstream one)
________________________________
From: Delta1977 ***@***.***>
Sent: Wednesday, November 15, 2023 12:48 PM
To: MaxWinterstein/homeassistant-addons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MaxWinterstein/homeassistant-addons] CUPS Addon (Issue #217)


Hi, actual Cups-Addon did not save settings like Printer and so on.

**Comment by MaxWinterstein** [comment]
This should be fixed with the release of the `cups` addon v3 - I deceided to ditch the 'dev' version and go straigt into the main cups addon.

Please have a look.

**Comment by Delta1977** [comment]
Thank you for your work. 
I will give a try later and give you a feedback

**Comment by Delta1977** [comment]
Nice work. 
Running one day without problems

Can you add HA ingress for webinterface in a next step?

**Comment by MaxWinterstein** [comment]
> Can you add HA ingress for webinterface in a next step?

Gave it a quick try, but having weird issues, even restarts of Home Assistant. I have this on my list, but with a lower prio (for now)
