### ISSUE TITLE
Latest Version

### ISSUE THREAD

**Issue by akeslo** [MaxWinterstein/homeassistant-addons#32]
Does this auto pull the latest version from matijse repository? https://github.com/matijse/eufy-ha-mqtt-bridge

I'm seeing the following in my logs:
"[16:25:59] INFO: Image build with version 0.2.17" however latest version on matijse repository is 0.2.18.

If it's not pulling the latest version, how do I go about updating?

Thank you very much!

**Comment by MaxWinterstein** [comment]
They should be in sync. This repo is notified via some trigger when a new release is available and generates the update.

Can you show me some more log output? 

This is mine:


![Screen Shot 2021-06-19 at 00 06 48](https://user-images.githubusercontent.com/5927148/122620212-a5c6bd80-d092-11eb-8b44-7664ac59c08a.png)

**Comment by akeslo** [comment]
Ok thank you!  Here is my log:

![image](https://user-images.githubusercontent.com/3003773/122644156-d71aaa00-d0e1-11eb-80b1-a69bef6ebc40.png)

**Comment by matijse** [comment]
@MaxWinterstein in order to include a new image processing library, I've had to add many things to the Dockerfile to get it to work on all architectures. See also this issue: https://github.com/matijse/eufy-ha-mqtt-bridge/issues/68

And the current Dockerfile: https://github.com/matijse/eufy-ha-mqtt-bridge/blob/main/Dockerfile

I see this breaks your pipeline, as the latest release fails... I hope this works when you add the changes to your Dockerfile as well...

**Comment by MaxWinterstein** [comment]
@akeslo can you try with the latest release `1.19.0` and show me the logs?

@matijse I just adjusted the base image to some more recent one. `0.2.19` works fine for me now. At least on `amd64` and `arch64` tested.

**Comment by MaxWinterstein** [comment]
@matijse seems like i was wrong, armv7 is broken indeed as there are no prebuild binaries. Sorry ✌️

**Comment by MaxWinterstein** [comment]
@akeslo or the new `1.20.0`?

**Comment by akeslo** [comment]
@MaxWinterstein Thank you - just upgraded to 1.20.0, this looks good now!

![image](https://user-images.githubusercontent.com/3003773/124928498-a2f22500-dfcd-11eb-879d-3afefbde5d4d.png)

**Comment by MaxWinterstein** [comment]
Awesome! No idea what happened here in the first place...

/close
